const ROOM_PUBLIC=true;
const ROOM_API='https://teshuva-pnima-keren-2026.immamagshima.chatgpt.site',ROOM_KEY='teshuva-live-room-v1';
let liveRoom=null,remoteRows=[],roomClosed=false,pollBusy=false,lastSuccess=0,includeLegacy=false;
try{liveRoom=JSON.parse(localStorage.getItem(ROOM_KEY)||'null')}catch{}
if(location.hash.startsWith('#host=')){try{const candidate=JSON.parse(decodeURIComponent(location.hash.slice(6)));if(candidate.id&&/^[a-f0-9]{64}$/.test(candidate.admin)&&/^[a-f0-9]{64}$/.test(candidate.submit)){liveRoom=candidate;localStorage.setItem(ROOM_KEY,JSON.stringify(liveRoom));history.replaceState(null,'',location.pathname+location.search)}}catch{}}
function roomLink(){return liveRoom?ROOM_API+'/join#room='+encodeURIComponent(liveRoom.id)+'&key='+liveRoom.submit:''}
function allSongLines(){return liveRoom?[...(includeLegacy?lines:[]),...remoteRows.map(x=>x.body)]:lines}
async function liveRequest(path,options={}){const r=await fetch(ROOM_API+'/api/rooms'+path,{...options,headers:{'Content-Type':'application/json',...(liveRoom?{Authorization:'Bearer '+liveRoom.admin}:{})}});if(!(r.headers.get('Content-Type')||'').includes('application/json'))throw Error('איסוף המשפטים עדיין אינו פתוח לקהל.');const data=await r.json();if(!r.ok)throw Error(data.error||'לא הצלחנו להתחבר למרחב.');return data}
function liveMessage(t){$('liveStatus').textContent=t}
function liveUI(){const active=!!liveRoom;if(!ROOM_PUBLIC&&location.origin!==ROOM_API){$('createRoom').disabled=true;liveMessage('קישור האיסוף מחכה לפתיחת אתר המפגש לקהל. אפשר להכין את המרחב באתר הפרטי של קרן.');}$('createRoom').hidden=active;$('roomActive').hidden=!active;$('joinLink').value=roomLink();$('closeRoom').textContent=roomClosed?'לפתוח שוב את האיסוף':'לסגור את האיסוף';$('liveCount').textContent=(remoteRows.length===1?'שורה אחת הגיעה':remoteRows.length+' שורות הגיעו')+(roomClosed?' · האיסוף סגור':'');const list=$('liveRows');list.replaceChildren();remoteRows.forEach(row=>{const item=document.createElement('div');item.className='live-row';const p=document.createElement('p');p.textContent=row.body;const b=document.createElement('button');b.textContent='להסיר';b.onclick=async()=>{b.disabled=true;try{await liveRequest('/'+liveRoom.id+'/lines/'+row.id,{method:'DELETE'});await syncRoom()}catch(e){liveMessage(e.message);b.disabled=false}};item.append(p,b);list.append(item)});renderWall();updateSongInvite()}
async function syncRoom(){if(!liveRoom||pollBusy)return;pollBusy=true;try{const data=await liveRequest('/'+liveRoom.id+'/lines');const changed=JSON.stringify(remoteRows)!==JSON.stringify(data.lines)||roomClosed!==data.closed;remoteRows=data.lines;roomClosed=data.closed;lastSuccess=Date.now();$('liveState').textContent=roomClosed?'האיסוף הסתיים':(remoteRows.length===1?'שורה אחת הגיעה':remoteRows.length+' שורות הגיעו')+' · מתעדכן מהמשתתפות';liveMessage('המרחב מחובר. השורות מגיעות אוטומטית.');if(changed||$('roomActive').hidden)liveUI()}catch(e){$('liveState').textContent='העדכון נעצר. בודקות את החיבור…';liveMessage(e.message+' השורות שכבר הגיעו נשארות על המסך.')}finally{pollBusy=false}}
window.openLiveRoom=()=>{state.running=false;paint();save();if($('tools').open)$('tools').close();$('liveRoom').showModal();liveUI();syncRoom()};
$('createRoom').onclick=async()=>{const b=$('createRoom');b.disabled=true;liveMessage('פותחות מקום למילים…');try{liveRoom=await liveRequest('',{method:'POST'});try{localStorage.setItem(ROOM_KEY,JSON.stringify(liveRoom))}catch{liveMessage('המרחב נפתח. שמרי את קישור הניהול הפרטי לפני שתסגרי את הדפדפן.')}await syncRoom()}catch(e){liveMessage(e.message)}finally{b.disabled=false}};
async function copyLive(text,message){try{await navigator.clipboard.writeText(text);liveMessage(message)}catch{ $('copyFallback').hidden=false;$('copyFallback').value=text;$('copyFallback').focus();$('copyFallback').select();liveMessage('הטקסט מוכן להעתקה מהתיבה.')}}
$('copyJoin').onclick=()=>copyLive(roomLink(),'קישור המשתתפות הועתק. אפשר לשלוח אותו בצ׳אט של הזום או בוואטסאפ.');
$('copyHost').onclick=()=>copyLive(location.origin+location.pathname+'#host='+encodeURIComponent(JSON.stringify(liveRoom)),'קישור הניהול הפרטי הועתק. שמרי אותו לעצמך בלבד.');
$('copyLivePrompt').onclick=()=>{if(!allSongLines().length)return liveMessage('עדיין לא הגיעו שורות לשיר.');copyLive(productionPrompt(),'הועתקו כל השורות עם פרומפט ההפקה. אפשר להדביק בצ׳אט להכנת השיר.')};
$('copyLiveLines').onclick=()=>{if(!allSongLines().length)return liveMessage('עדיין לא הגיעו שורות.');copyLive(songText(),'כל השורות הועתקו.')};
$('closeRoom').onclick=async()=>{try{await liveRequest('/'+liveRoom.id,{method:'PATCH',body:JSON.stringify({closed:!roomClosed})});await syncRoom()}catch(e){liveMessage(e.message)}};
$('deleteRoom').onclick=async()=>{if(!confirm('למחוק את המרחב ואת כל השורות שנשלחו אליו? שמרי קודם את המילים שתרצי לקחת.'))return;try{await liveRequest('/'+liveRoom.id,{method:'DELETE'});liveRoom=null;remoteRows=[];localStorage.removeItem(ROOM_KEY);liveUI();liveMessage('המרחב נמחק.')}catch(e){liveMessage(e.message)}};
$('manualImport').onclick=()=>{includeLegacy=true;$('liveRoom').close();openLegacyCollector()};
function updateSongInvite(){const active=!!liveRoom&&!roomClosed&&current().songLink&&!state.ground;$('songInvite').hidden=!active;$('liveState').hidden=document.body.dataset.visual!=='wall'||!liveRoom;if(active){$('participantLink').href=roomLink();$('participantLink').textContent='פתיחת הקישור לשורה';} }
setInterval(syncRoom,4000);syncRoom();updateSongInvite();

/* Direct, persistent collection controls. Admin tokens never enter the public link. */
(()=>{const bar=document.createElement('section');bar.className='song-live-controls';bar.setAttribute('aria-label','המילים שלנו');document.querySelector('nav').before(bar);const copy=document.createElement('button'),show=document.createElement('button'),all=document.createElement('button'),status=document.createElement('p'),fallback=document.createElement('textarea');copy.id='copyParticipantLink';show.id='showCollectiveWords';all.id='copySongWords';fallback.hidden=true;fallback.readOnly=true;status.setAttribute('role','status');bar.append(copy,show,all,status,fallback);const onward=document.createElement('button');onward.id='continueFromWords';onward.className='primary';onward.textContent='להמשך המפגש ←';bar.append(onward);
 const screen=document.createElement('section');screen.className='collective-screen';screen.hidden=true;screen.innerHTML='<h1>הסליחות שלנו</h1><p class="small">כל שורה מוצאת כאן מקום.</p><div class="collective-lines"></div>';document.getElementById('stage').before(screen);let view=false,signature='',busy=false;
 async function clipboard(text,message){if(!text){status.textContent='עדיין לא הגיעו שורות.';return}try{await navigator.clipboard.writeText(text);status.textContent=message;toast(message)}catch{fallback.hidden=false;fallback.value=text;fallback.focus();fallback.select();status.textContent='הטקסט מוכן להעתקה בתיבה.'}}
 function update(){onward.hidden=!(view||current().visual==='wall');copy.textContent=liveRoom?'העתקת הקישור למשתתפות':'פתיחת איסוף והעתקת קישור';show.textContent=view?'חזרה למסע':'המילים שלנו';all.textContent='העתקת השורות לשיר';bar.hidden=!(view||current().songLink||['wall','music'].includes(current().visual));if(bar.hidden){status.textContent='';fallback.hidden=true;}const content=allSongLines(),sig=JSON.stringify(content);if(sig!==signature){signature=sig;const grid=screen.querySelector('.collective-lines');grid.replaceChildren();if(!content.length){const empty=document.createElement('p');empty.textContent='המילים שלכן יגיעו לכאן.';grid.append(empty)}content.forEach((text,i)=>{const item=document.createElement('p');item.textContent=text;item.style.setProperty('--line-delay',(-i*2.3)+'s');grid.append(item)})}}
 copy.onclick=async()=>{if(busy)return;busy=true;copy.disabled=true;try{if(!liveRoom){liveRoom=await liveRequest('',{method:'POST'});localStorage.setItem(ROOM_KEY,JSON.stringify(liveRoom));await syncRoom()}if(roomClosed){await liveRequest('/'+liveRoom.id,{method:'PATCH',body:JSON.stringify({closed:false})});await syncRoom()}await clipboard(roomLink(),'הקישור הועתק. אפשר לשתף בצ׳אט של הזום.')}catch(e){status.textContent=e.message}finally{busy=false;copy.disabled=false;update()}};
 show.onclick=()=>{view=!view;screen.hidden=!view;document.body.classList.toggle('viewing-lines',view);update();window.scrollTo({top:0,behavior:'smooth'})};all.onclick=()=>clipboard(songText(),'כל השורות הועתקו לשיר.');onward.onclick=()=>{if(view)show.click();document.getElementById('next').click()};
 const originalInvite=window.updateSongInvite;window.updateSongInvite=()=>{originalInvite();update();if(current().songLink)$('participantLink').hidden=true};const previous=window.updateQuietMotion;window.updateQuietMotion=()=>{previous?.();update()};
 document.getElementById('stageAction').addEventListener('click',e=>{if(document.body.dataset.visual==='wall'){e.stopImmediatePropagation();show.click()}},true);setInterval(update,1500);update();
})();

(()=>{const settings=document.getElementById('songSettings');settings.open=true;settings.hidden=current().visual!=='music';document.getElementById('stageAction').after(settings)})();
