const ROOM_PUBLIC=false;
const ROOM_API='https://teshuva-pnima-keren-2026.immamagshima.chatgpt.site',ROOM_KEY='teshuva-live-room-v1';
let liveRoom=null,remoteRows=[],roomClosed=false,pollBusy=false,lastSuccess=0,includeLegacy=false;
try{liveRoom=JSON.parse(localStorage.getItem(ROOM_KEY)||'null')}catch{}
if(location.hash.startsWith('#host=')){try{const candidate=JSON.parse(decodeURIComponent(location.hash.slice(6)));if(candidate.id&&/^[a-f0-9]{64}$/.test(candidate.admin)&&/^[a-f0-9]{64}$/.test(candidate.submit)){liveRoom=candidate;localStorage.setItem(ROOM_KEY,JSON.stringify(liveRoom));history.replaceState(null,'',location.pathname+location.search)}}catch{}}
function roomLink(){return liveRoom?ROOM_API+'/join#room='+encodeURIComponent(liveRoom.id)+'&key='+liveRoom.submit:''}
function allSongLines(){return liveRoom?[...(includeLegacy?lines:[]),...remoteRows.map(x=>x.body)]:lines}
async function liveRequest(path,options={}){const r=await fetch(ROOM_API+'/api/rooms'+path,{...options,headers:{'Content-Type':'application/json',...(liveRoom?{Authorization:'Bearer '+liveRoom.admin}:{})}});if(!(r.headers.get('Content-Type')||'').includes('application/json'))throw Error('איסוף המשפטים עדיין אינו פתוח לקהל.');const data=await r.json();if(!r.ok)throw Error(data.error||'לא הצלחנו להתחבר למרחב.');return data}
function liveMessage(t){$('liveStatus').textContent=t}
function liveUI(){const active=!!liveRoom;if(!ROOM_PUBLIC&&location.origin!==ROOM_API){$('createRoom').disabled=true;liveMessage('קישור האיסוף מחכה לפתיחת אתר המפגש לקהל. אפשר להכין את המרחב באתר הפרטי של קרן.');}$('createRoom').hidden=active;$('roomActive').hidden=!active;$('joinLink').value=roomLink();$('closeRoom').textContent=roomClosed?'לפתוח שוב את האיסוף':'לסגור את האיסוף';$('liveCount').textContent=(remoteRows.length===1?'שורה אחת הגיעה':remoteRows.length+' שורות הגיעו')+(roomClosed?' · האיסוף סגור':'');const list=$('liveRows');list.replaceChildren();remoteRows.forEach(row=>{const item=document.createElement('div');item.className='live-row';const p=document.createElement('p');p.textContent=row.body;const b=document.createElement('button');b.textContent='להסיר';b.onclick=async()=>{b.disabled=true;try{await liveRequest('/'+liveRoom.id+'/lines/'+row.id,{method:'DELETE'});await syncRoom()}catch(e){liveMessage(e.message);b.disabled=false}};item.append(p,b);list.append(item)});renderWall();updateSongInvite()}
async function syncRoom(){if(!liveRoom||pollBusy)return;pollBusy=true;try{const data=await liveRequest('/'+liveRoom.id+'/lines');const changed=JSON.stringify(remoteRows)!==JSON.stringify(data.lines)||roomClosed!==data.closed;remoteRows=data.lines;roomClosed=data.closed;lastSuccess=Date.now();$('liveState').textContent=roomClosed?'האיסוף הסתיים':(remoteRows.length===1?'שורה אחת הגיעה':remoteRows.length+' שורות הגיעו')+' · מתעדכן מהמשתתפות';liveMessage('המרחב מחובר. השורות מגיעות אוטומטית.');if(changed||$('roomActive').hidden)liveUI()}catch(e){$('liveState').textContent='העדכון נעצר. בודקות את החיבור…';liveMessage(e.message+' השורות שכבר הגיעו נשארות על המסך.')}finally{pollBusy=false}}
window.openLiveRoom=()=>{state.running=false;paint();save();if($('tools').open)$('tools').close();$('liveRoom').showModal();liveUI();syncRoom()};
$('createRoom').onclick=async()=>{const b=$('createRoom');b.disabled=true;liveMessage('פותחות מקום למילים…');try{liveRoom=await liveRequest('',{method:'POST'});try{localStorage.setItem(ROOM_KEY,JSON.stringify(liveRoom))}catch{liveMessage('המרחב נפתח. שמרי את קישור הניהול הפרטי לפני שתסגרי את הדפדפן.')}await syncRoom()}catch(e){liveMessage(e.message)}finally{b.disabled=false}};
async function copyLive(text,message){try{await navigator.clipboard.writeText(text);liveMessage(message)}catch{ $('copyFallback').hidden=false;$('copyFallback').value=text;$('copyFallback').focus();$('copyFallback').select();liveMessage('הטקסט מוכן להעתקה מהתיבה.')}}
$('copyJoin').onclick=()=>copyLive(roomLink(),'קישור המשתתפות הועתק. אפשר לשלוח אותו בצ׳אט של הזום או בוואטסאפ.');
$('copyHost').onclick=()=>copyLive(location.origin+location.pathname+'#host='+encodeURIComponent(JSON.stringify(liveRoom)),'קישור הניהול הפרטי הועתק. שמרי אותו לעצמך בלבד.');
$('copyLivePrompt').onclick=()=>{if(!allSongLines().length)return liveMessage('עדיין לא הגיעו שורות לשיר.');copyLive(productionPrompt(),'הועתקו כל השורות עם פרומפט ההפקה. אפשר להדביק בצ׳אט להכנת השיר.')};
$('copyLiveLines').onclick=()=>{if(!allSongLines().length)return liveMessage('עדיין לא הגיעו שורות.');copyLive(songText(),'כל השורות הועתקו.')};
$('closeRoom').onclick=async()=>{try{await liveRequest('/'+liveRoom.id,{method:'PATCH',body:JSON.stringify({closed:!roomClosed})});await syncRoom()}catch(e){liveMessage(e.message)}};
$('deleteRoom').onclick=async()=>{if(!confirm('למחוק את המרחב ואת כל השורות שנשלחו אליו? שמרי קודם את המילים שתרצי לקחת.'))return;try{await liveRequest('/'+liveRoom.id,{method:'DELETE'});liveRoom=null;remoteRows=[];localStorage.removeItem(ROOM_KEY);liveUI();liveMessage('המרחב נמחק.')}catch(e){liveMessage(e.message)}};
$('manualImport').onclick=()=>{includeLegacy=true;$('liveRoom').close();openLegacyCollector()};
function updateSongInvite(){const active=!!liveRoom&&!roomClosed&&current().songLink&&!state.ground;$('songInvite').hidden=!active;$('liveState').hidden=document.body.dataset.visual!=='wall'||!liveRoom;if(active){$('participantLink').href=roomLink();$('participantLink').textContent='פתיחת הקישור לשורה';} }
setInterval(syncRoom,4000);syncRoom();updateSongInvite();
